apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: app-a
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello
          image: "660387449292.dkr.ecr.us-east-2.amazonaws.com/joseret-repo1:v0.0.2"
          command: ["python3"]
          args: ["gcs_list_files.py", "jr-network-infra-1-4978-info1"]
          env:
            - name: "PORT"
              value: "8080"
